name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      GOODLE_ID: ${{secrets.GOODLE_ID}}
      GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Set pnpm version
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 7
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Start Server
        run: pnpm dev & sleep 10
      - name: Run Cypress Tests
        run: pnpm cypress:run
